# Generated by Django 4.1.3 on 2022-11-05 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('from_som', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from+', to='apka.profile')),
                ('to_som', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='apka.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='apka.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apka.profile')),
            ],
        ),
    ]
